import { Bai_Jamjuree } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const BaiJamjuree = Bai_Jamjuree({
  weight: ["400"],
});
export const fontBangla = localFont({
  src: "./../fonts/mayaboti-Italic.ttf",
});

export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${BaiJamjuree.className}  antialiased`}>
        <header>
          <Navbar></Navbar>
        </header>
        <div className=" h-[80px]"></div>
        <main
          className="

  min-h-[calc(100vh-302px)]

"
        >
          {children}
        </main>

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
