import { Bai_Jamjuree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const BaiJamjuree = Bai_Jamjuree({
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${BaiJamjuree.className}  antialiased`}>
        <header>
          <Navbar></Navbar>
        </header>
        <div className=" h-[85px]"></div>
        <main
          className="
  mx-auto
  max-w-11/12
  min-h-[calc(100vh-302px)]

"
        >
          {children}
        </main>

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
